### ISSUE TITLE
麻烦支持下Android Studio Chipmunk 2021.2.1 patch 1

### ISSUE THREAD

**Issue by PiPiPaPa01** [yuanhoujun/intellij-generate-serial-version-uid-plugin#2]

**Comment by yuanhoujun** [comment]
@JimmyZou92 0.2.2版本已支持，等JetBrains审核通过后就可以下载使用了，谢谢你的反馈。

**Comment by PiPiPaPa01** [comment]
十分感谢你

**Comment by yuanhoujun** [comment]
不用客气 直接下载jar包安装使用 兼容性问题懒得弄了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月18日(周一) 晚上8:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [yuanhoujun/intellij-generate-serial-version-uid-plugin] 麻烦支持下Android Studio Chipmunk 2021.2.1 patch 1 (Issue #2)




 
十分感谢你
